version: '3.9'

services:
  app:
    build: .
    container_name: fastapi-dice
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
